apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  description: The place to be, for great artists
  annotations:
    github.com/project-slug: 'tataebusiness/backstage_toolkit'
spec:
  type: website
  lifecycle: production
  owner: idpadmins
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  dependencyOf:
    - system:default/examples
  providesApis:
    - artist-api
