apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: readers
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: Readers
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: idpadmins
  children: []
  members: []
  
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: Developers
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: idpadmins
  children: []
  members: [tataebusiness]

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: idpadmins
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: IDP Admins
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: []
  children: [developers, readers]
  members: [tataebusiness]

