apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-with-docs
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  owner: idpadmins
  lifecycle: production
